spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/ToolsForCostEngineer?useUnicode=true&characterEncoding=utf-8
    username: root
    password: y8658641c

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB